language: r
cache: packages

dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q

apt_packages:
  - libssl-dev
  - libcurl4-openssl-dev
  - netcdf-bin
  - libnetcdf-dev
  - gdal-bin
  - libgdal-dev
  - libudunits2-dev
  - libproj-dev
  - libgeos-dev

r_packages:
  - rgdal

bioc_packages:
  - rhdf5

r_github_packages:
  - jimhester/covr

after_success:
  - R -e 'covr::codecov(quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change
