language: r
cache: packages

dist: trusty
sudo: required

addons:
  apt:
    packages:
     - r-cran-rgdal

r_packages:
  - rgdal

bioc_packages:
  - rhdf5

r_github_packages:
  - jimhester/covr

after_success:
  - R -e 'covr::codecov(quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change
