language: c
sudo: required
dist: trusty

before_script:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libv8-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps

script:
  - ./travis-tool.sh run_tests

install_r:
  - covr

install_bioc:
  - rhdf5

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

after_success:
  - Rscript -e 'covr::codecov()'

after_script:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
