language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      latex: false
      osx_image: xcode8.1
    - os: osx
      latex: false
      osx_image: xcode8.1
      disable_homebrew: true
    - os: osx
      latex: false
      osx_image: beta-xcode6.1
      disable_homebrew: true

addons:
  apt:
    packages:
     - r-cran-rgdal

r_packages:
  - rgdal

bioc_packages:
  - rhdf5

r_github_packages:
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
